import BookModel from "../model/book.model";
import connect from "../utils/connect";
import loggerUtil from "../utils/logger";

const books = [
  {
    name: "The Art of Programming",
    description:
      "A comprehensive guide to modern software development practices",
    image: "https://example.com/art-programming.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Digital Innovation",
    description:
      "Exploring the latest trends in technology and digital transformation",
    image: "https://example.com/digital-innovation.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cloud Architecture Mastery",
    description: "Deep dive into cloud computing and distributed systems",
    image: "https://example.com/cloud-arch.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Data Science Fundamentals",
    description: "Essential concepts in data analysis and machine learning",
    image: "https://example.com/data-science.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Web Development Mastery",
    description: "Full-stack web development from ground up",
    image: "https://example.com/web-dev.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mobile App Development",
    description: "Creating powerful mobile applications",
    image: "https://example.com/mobile-dev.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "DevOps Handbook",
    description: "Modern DevOps practices and implementations",
    image: "https://example.com/devops.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Artificial Intelligence Basics",
    description: "Introduction to AI and its applications",
    image: "https://example.com/ai-basics.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Blockchain Technology",
    description: "Understanding distributed ledger technology",
    image: "https://example.com/blockchain.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cybersecurity Essentials",
    description: "Fundamental security practices for modern systems",
    image: "https://example.com/cybersecurity.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Python Programming",
    description: "Mastering Python for various applications",
    image: "https://example.com/python.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "JavaScript Deep Dive",
    description: "Advanced concepts in JavaScript programming",
    image: "https://example.com/javascript.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "React Framework",
    description: "Building modern web applications with React",
    image: "https://example.com/react.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Node.js Backend",
    description: "Server-side development with Node.js",
    image: "https://example.com/nodejs.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Database Design",
    description: "Principles of database architecture",
    image: "https://example.com/database.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Machine Learning Projects",
    description: "Hands-on machine learning implementations",
    image: "https://example.com/ml-projects.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Software Architecture",
    description: "Designing scalable software systems",
    image: "https://example.com/software-arch.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "UI/UX Design",
    description: "Creating effective user interfaces",
    image: "https://example.com/ui-ux.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Docker Containers",
    description: "Containerization and orchestration",
    image: "https://example.com/docker.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Git Version Control",
    description: "Advanced git workflows and collaboration",
    image: "https://example.com/git.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Angular Framework",
    description: "Enterprise applications with Angular",
    image: "https://example.com/angular.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Vue.js Development",
    description: "Building reactive web interfaces",
    image: "https://example.com/vuejs.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "TypeScript Programming",
    description: "Type-safe JavaScript development",
    image: "https://example.com/typescript.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "REST API Design",
    description: "Building robust REST APIs",
    image: "https://example.com/rest-api.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "GraphQL Advanced",
    description: "Modern API development with GraphQL",
    image: "https://example.com/graphql.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Microservices Architecture",
    description: "Designing distributed systems",
    image: "https://example.com/microservices.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "AWS Cloud Services",
    description: "Amazon Web Services implementation",
    image: "https://example.com/aws.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Azure Solutions",
    description: "Microsoft Azure cloud platform",
    image: "https://example.com/azure.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Google Cloud Platform",
    description: "GCP services and solutions",
    image: "https://example.com/gcp.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Linux Administration",
    description: "Managing Linux systems effectively",
    image: "https://example.com/linux.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Network Security",
    description: "Securing network infrastructure",
    image: "https://example.com/network-security.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ethical Hacking",
    description: "Penetration testing and security",
    image: "https://example.com/ethical-hacking.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Data Analytics",
    description: "Business intelligence and analytics",
    image: "https://example.com/data-analytics.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Big Data Processing",
    description: "Handling large-scale data systems",
    image: "https://example.com/big-data.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "IoT Development",
    description: "Internet of Things applications",
    image: "https://example.com/iot.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "5G Technology",
    description: "Next-generation mobile networks",
    image: "https://example.com/5g.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Quantum Computing",
    description: "Introduction to quantum systems",
    image: "https://example.com/quantum.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rust Programming",
    description: "Systems programming with Rust",
    image: "https://example.com/rust.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Go Language",
    description: "Building efficient applications with Go",
    image: "https://example.com/golang.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Swift Development",
    description: "iOS and macOS application development",
    image: "https://example.com/swift.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kotlin Programming",
    description: "Modern Android development",
    image: "https://example.com/kotlin.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Flutter Framework",
    description: "Cross-platform mobile development",
    image: "https://example.com/flutter.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "React Native",
    description: "Mobile apps with React Native",
    image: "https://example.com/react-native.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Unity Game Development",
    description: "Creating interactive games",
    image: "https://example.com/unity.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Unreal Engine",
    description: "Advanced game development",
    image: "https://example.com/unreal.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "3D Modeling",
    description: "Digital asset creation",
    image: "https://example.com/3d-modeling.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "AR/VR Development",
    description: "Augmented and Virtual Reality",
    image: "https://example.com/ar-vr.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Computer Vision",
    description: "Image processing and recognition",
    image: "https://example.com/computer-vision.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Natural Language Processing",
    description: "Text analysis and processing",
    image: "https://example.com/nlp.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Robotics Programming",
    description: "Building and programming robots",
    image: "https://example.com/robotics.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Deep Learning",
    description: "Neural networks and deep learning",
    image: "https://example.com/deep-learning.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Embedded Systems",
    description: "Programming microcontrollers",
    image: "https://example.com/embedded.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seed() {
  await connect();
  await BookModel.deleteMany();
  await BookModel.insertMany(books);
  loggerUtil.info("Seed completed successfully!");
  process.exit(0);
}

seed();
